# Generated by Django 4.2.29 on 2026-03-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="iacomponent",
            name="iacomponent_course_name_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="marksentry",
            name="marksentry_student_component_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="program",
            name="program_school_short_name_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="resultsheet",
            name="resultsheet_student_course_uniq",
        ),
        migrations.RemoveConstraint(
            model_name="studentenrolment",
            name="studentenrolment_student_course_year_uniq",
        ),
        migrations.AddField(
            model_name="ccr",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="facultyof",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="iacomponent",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="marksentry",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="resultsheet",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="studentenrolment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="iacomponent",
            unique_together={("course", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="marksentry",
            unique_together={("student", "component")},
        ),
        migrations.AlterUniqueTogether(
            name="program",
            unique_together={("school", "short_name")},
        ),
        migrations.AlterUniqueTogether(
            name="resultsheet",
            unique_together={("student", "course")},
        ),
        migrations.AlterUniqueTogether(
            name="studentenrolment",
            unique_together={("student", "course", "academic_year")},
        ),
    ]
